### ISSUE TITLE
provide better diagnostics when  spawning phantom fails

### ISSUE THREAD

**Issue by markstos** [e-conomic/phantom-render-stream#14]
Currently spawning phantom fails like this:

    Error: spawn ENOENT
        at errnoException (child_process.js:998:11)
        at Process.ChildProcess._handle.onexit (child_process.js:789:34)

It would be more helpful if the full path the phantom attempted was provided since it's the source of the "ENOENT" error. ("Error No Entity"). 

I need this, so I might add it myself shortly. 

The issue can reproduced by temporarily updating the call to phantom like this:

       child = cp.spawn('/BOOM', [path.join(__dirname, 'phantom-process.js'), filename]);

**Comment by hulvei3** [comment]
see #95
