### ISSUE TITLE
Behavior of exceeding 'pool' size should be documented

### ISSUE THREAD

**Issue by markstos** [e-conomic/phantom-render-stream#42]
The behavior of exceeding having the number of incoming requests exceed the  'pool' size should be documented.  

Are the requests queued? Dropped? If they are queued, is the queue size infinite or bounded?

**Comment by hulvei3** [comment]
That seems to be correct.

I don't know if it make sense to have a queue limit. Maybe as an opt-in?
And then it could return a 503 if the queues on all workers are "full"..

**Comment by markstos** [comment]
If there is no queue limit, then it seems that there's a potential attack vector to denial of service, or other problems due to exhausting all memory.

Defaulting to a high limit seems like a safe option. It would be unlikely to be encountered in normal usage, but would will be a safeguard an exceptionally large number items in the queue.
