### ISSUE TITLE
Wish: Support for PhantomJS 2.0

### ISSUE THREAD

**Issue by markstos** [e-conomic/phantom-render-stream#86]
The changes will hopefully be easy here, but the work is currently blocked by the `phantomjs` dependency, which [doesn't yet set support PhantomJS 2.0](https://github.com/Medium/phantomjs/issues/288).

Note: as workaround there's a [fork of this module](https://github.com/w3dot0/phantom2-render-stream/commit/dc938f7efff29c68bda581398af0b4020440b786) which is made to use PhantomJS 2. 

Ideally one module would support both options for now. PhantomJS 2 doesn't yet support file uploads, so might not be suitable for all cases.

**Comment by davisford** [comment]
I hate the obligatory +1 posts, but I was just checking here to see if you had a branch or tag that used `phantomjs2` instead of `phantomjs`...otherwise I was going to update my fork to do so.  Can you just create a quick branch that pulls in `phantomjs2` instead of `phantomjs` so we can experiment with it?

**Comment by markstos** [comment]
@davisford What version of `npm` was giving you ENOENT problems? Note that `npm 3.5.2` [fixed some ENOENT bugs](https://github.com/npm/npm/blob/master/CHANGELOG.md)

**Comment by markstos** [comment]
@davisford besides a `phantomjs2` package, there is also a `phantomjs2.0` package to try. I haven't tried either yet:

https://www.npmjs.com/package/phantomjs2
https://www.npmjs.com/package/phantomjs2.0

**Comment by davisford** [comment]
I'm on `npm@3.4.1`, but there is a [specific issue on the phantomjs2](https://github.com/zeevl/phantomjs2/pull/7) repo about this one that i'm hitting.  I'll try to upgrade npm though -- thanks for the tips also with `phantomjs2.0`

**Comment by joelmukuthu** [comment]
The good news is that as of two days ago, the latest version of `phantomjs` (2.1.2) now installs `PhantomJS 2` :)

**Comment by hulvei3** [comment]
fixed by #93
