### ISSUE TITLE
It is possible to specify the viewPortSize?

### ISSUE THREAD

**Issue by IonicaBizau** [e-conomic/phantom-render-stream#90]
I'm working on a new version of [`nodeice`](https://github.com/IonicaBizau/nodeice) adding streams support.

I would like to use this library, but I'm not sure if it supports the `viewPortSize` option [which is used here](https://github.com/IonicaBizau/nodeice/blob/69405c911aacd6f667fd9a0da2e444d764728584/index.js#L207).

So, is it possible to specify the `viewPortSize`?

**Comment by jadware** [comment]
You should be able to use the `width` and `height` options to explicity set the viewport size.  You can also try using `paperSize` and `orientation` and `format`, but I've had the most consistency with `width` and `height`.

To get the right number of pixels for a given page size, you can multiply the number of inches by DPI (72 typically).

**Comment by IonicaBizau** [comment]
:+1: Thanks! Will give it a try!
