### ISSUE TITLE
How to insert custom HTML which comes from a non-file?

### ISSUE THREAD

**Issue by IonicaBizau** [e-conomic/phantom-render-stream#91]
I have a variable which contains the HTML snippet which should be rendered as pdf. Is it possible to pipe it or send it to this module, without using a file? 

Thanks! :cake:

**Comment by jadware** [comment]
You need to create a stream, fill it with your html, and then pipe it to the render function.  Here's an example:
```
var instream = new stream.PassThrough();
instream.end(html);
instream.pipe(render(opts));
```

**Comment by IonicaBizau** [comment]
Sounds good! :+1: 

Could you please take a look at https://github.com/e-conomic/phantom-render-stream/issues/90 too? 

Thanks!
